# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-18 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='Cards',
            field=models.TextField(max_length=30),
        ),
    ]
