# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-18 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20180318_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='Amount',
            new_name='amount',
        ),
    ]
