# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-18 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20180318_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='Cards',
            field=models.TextField(blank=True, null=True),
        ),
    ]
