# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-18 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20180318_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='amount',
            field=models.FloatField(blank=True),
        ),
    ]
